Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP # MSP ID
        MSPDir: ../artifacts/certs/ordererOrganizations/anvisa.gov.br/msp

    - &Industry
        Name: IndustryMSP
        ID: IndustryMSP
        MSPDir: ../artifacts/certs/peerOrganizations/industry.anvisa.gov.br/msp
        AnchorPeers:
            - Host: peer0.industry.anvisa.gov.br
              Port: 7051

    - &Provider
        Name: ProviderMSP
        ID: ProviderMSP
        MSPDir: ../artifacts/certs/peerOrganizations/provider.anvisa.gov.br/msp
        AnchorPeers:
            - Host: peer0.provider.anvisa.gov.br
              Port: 9051

    - &Drugstore
        Name: DrugstoreMSP
        ID: DrugstoreMSP
        MSPDir: ../artifacts/certs/peerOrganizations/drugstore.anvisa.gov.br/msp
        AnchorPeers:
            - Host: peer0.drugstore.anvisa.gov.br
              Port: 11051

    - &Buyer
        Name: BuyerMSP
        ID: BuyerMSP
        MSPDir: ../artifacts/certs/peerOrganizations/buyer.anvisa.gov.br/msp
        AnchorPeers:
            - Host: peer0.buyer.anvisa.gov.br
              Port: 13051

Orderer: &OrdererDefaults
    # Available types are "solo" and "kafka"
    OrdererType: solo
    Addresses:
        - orderer.anvisa.gov.br:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092
    Organizations:


Application: &ApplicationDefaults
    Organizations:

Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.  Set the value of the capability to true to require it.
    Global: &ChannelCapabilities
        # V1.1 for Global is a catchall flag for behavior which has been
        # determined to be desired for all orderers and peers running v1.0.x,
        # but the modification of which would cause incompatibilities.  Users
        # should leave this flag set to true.
        V1_1: true

    # Orderer capabilities apply only to the orderers, and may be safely
    # manipulated without concern for upgrading peers.  Set the value of the
    # capability to true to require it.
    Orderer: &OrdererCapabilities
        # V1.1 for Order is a catchall flag for behavior which has been
        # determined to be desired for all orderers running v1.0.x, but the
        # modification of which  would cause incompatibilities.  Users should
        # leave this flag set to true.
        V1_1: true

    # Application capabilities apply only to the peer network, and may be safely
    # manipulated without concern for upgrading orderers.  Set the value of the
    # capability to true to require it.
    Application: &ApplicationCapabilities
        # V1.1 for Application is a catchall flag for behavior which has been
        # determined to be desired for all peers running v1.0.x, but the
        # modification of which would cause incompatibilities.  Users should
        # leave this flag set to true.
        V1_1: true

Profiles:
    GenesisBlockGeneration:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Industry
                - *Provider
                - *Drugstore
                - *Buyer
        
    ChannelCreation:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Industry
                - *Provider
                - *Drugstore
                - *Buyer
            Capabilities:
                <<: *ApplicationCapabilities
