version: '2'

services:
  ca:
    container_name: ca.drugstore.anvisa.gov.br
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-drugstore
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/ca.drugstore.anvisa.gov.br-cert.pem --ca.keyfile /etc/hyperledger/bfb857049cf12efd8b52ba0c112413013d82404bf405bfeb0d56235da3e040e0_sk -b admin:adminpw -d'
    volumes:
      - ../artifacts/certs/peerOrganizations/drugstore.anvisa.gov.br/ca:/etc/hyperledger


  peer0-db:
    container_name: peer0-db.drugstore.anvisa.gov.br
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=drugstorepeer0admin
      - COUCHDB_PASSWORD=pass

  peer1-db:
    container_name: peer1-db.drugstore.anvisa.gov.br
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=drugstorepeer1admin
      - COUCHDB_PASSWORD=pass


  peer0:
    container_name: peer0.drugstore.anvisa.gov.br
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.drugstore.anvisa.gov.br
      - CORE_PEER_ADDRESS=peer0.drugstore.anvisa.gov.br:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.drugstore.anvisa.gov.br:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.drugstore.anvisa.gov.br:7051
      - CORE_PEER_LOCALMSPID=DrugstoreMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-db.drugstore.anvisa.gov.br:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=drugstorepeer0admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/drugstore.anvisa.gov.br/peers/peer0.drugstore.anvisa.gov.br/msp:/etc/hyperledger/fabric/msp
    ports:
      - 11051:7051
      - 11053:7053

  peer1:
    container_name: peer1.drugstore.anvisa.gov.br
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.drugstore.anvisa.gov.br
      - CORE_PEER_ADDRESS=peer1.drugstore.anvisa.gov.br:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.drugstore.anvisa.gov.br:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.drugstore.anvisa.gov.br:7051
      - CORE_PEER_LOCALMSPID=DrugstoreMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-db.drugstore.anvisa.gov.br:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=drugstorepeer1admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/drugstore.anvisa.gov.br/peers/peer1.drugstore.anvisa.gov.br/msp:/etc/hyperledger/fabric/msp
    ports:
      - 12051:7051
      - 12053:7053