version: '2'

services:
  ca:
    container_name: ca.provider.anvisa.gov.br
    extends:
      file: base.yaml
      service: ca-base
    environment:
      - FABRIC_CA_SERVER_CA_NAME=ca-provider
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/ca.provider.anvisa.gov.br-cert.pem --ca.keyfile /etc/hyperledger/d02905a1eedf44cfd7abb9e1e82fc0dd2b923ed8d60aacab413ddc476c33194d_sk -b admin:adminpw -d'
    volumes:
      - ../artifacts/certs/peerOrganizations/provider.anvisa.gov.br/ca:/etc/hyperledger


  peer0-db:
    container_name: peer0-db.provider.anvisa.gov.br
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=providerpeer0admin
      - COUCHDB_PASSWORD=pass

  peer1-db:
    container_name: peer1-db.provider.anvisa.gov.br
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=providerpeer1admin
      - COUCHDB_PASSWORD=pass


  peer0:
    container_name: peer0.provider.anvisa.gov.br
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.provider.anvisa.gov.br
      - CORE_PEER_ADDRESS=peer0.provider.anvisa.gov.br:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.provider.anvisa.gov.br:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.provider.anvisa.gov.br:7051
      - CORE_PEER_LOCALMSPID=ProviderMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer0-db.provider.anvisa.gov.br:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=providerpeer0admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/provider.anvisa.gov.br/peers/peer0.provider.anvisa.gov.br/msp:/etc/hyperledger/fabric/msp
    ports:
      - 9051:7051
      - 9053:7053

  peer1:
    container_name: peer1.provider.anvisa.gov.br
    extends:
      file: base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.provider.anvisa.gov.br
      - CORE_PEER_ADDRESS=peer1.provider.anvisa.gov.br:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.provider.anvisa.gov.br:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.provider.anvisa.gov.br:7051
      - CORE_PEER_LOCALMSPID=ProviderMSP
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peer1-db.provider.anvisa.gov.br:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=providerpeer1admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    volumes:
        - /var/run/:/host/var/run/
        - ../artifacts/certs/peerOrganizations/provider.anvisa.gov.br/peers/peer1.provider.anvisa.gov.br/msp:/etc/hyperledger/fabric/msp
    ports:
      - 10051:7051
      - 10053:7053